/* GERADO por scripts/gerar-objecoes.mjs — não edite à mão.
 *
 * Catálogo nacional de objeções de venda de assinatura de veículos.
 * Prosa SEM NÚMERO de propósito: número envelhece e varia por contrato.
 * Os valores da simulação aberta aparecem numa faixa própria no Copiloto.
 *
 * ATENÇÃO ao usar: algumas falas descrevem regras de contrato (franquia,
 * participação em sinistro, carro reserva, prazo de saída). Cada locadora
 * precisa conferir se a redação bate com o contrato DELA antes de usar em
 * atendimento — prometer o que a empresa não pratica é o pior desfecho.
 */
import type { Familia } from './negociacao';

export interface ObjecaoEstatica {
  id: string;
  familia: Familia;
  rotulo: string;
  gatilhos: string[];
  fala: string;
  devolucao: string;
  evite: string;
}

export const CATALOGO_OBJECOES: ObjecaoEstatica[] = [
  {
    id: 'parcela-financiamento-menor',
    familia: 'preco',
    rotulo: 'A parcela do financiamento é menor',
    gatilhos: ['no financiamento fica menos', 'parcela do banco e menor', 'simulei no banco', 'financiando sai mais barato', 'o gerente me deu uma parcela menor', 'banco me deu melhor', 'consorcio sai menos', 'financiamento e mais em conta', 'vi a parcela do financiamento', 'meu gerente falou', 'simulacao do banco', 'fica mais barato financiar'],
    fala: 'A parcela do banco costuma ser menor porque ela paga só o carro. Fora dela ficam imposto, seguro, manutenção e a desvalorização na hora de vender. A comparação honesta é a parcela mais essas contas contra a mensalidade cheia.',
    devolucao: 'Podemos somar, do lado da parcela do banco, o que você pagaria à parte durante o ano?',
    evite: 'Atacar o financiamento. O cliente ouve que a escolha dele foi burra e fecha. Compare listas de custo, não produtos.',
  },
  {
    id: 'nao-cabe-orcamento',
    familia: 'preco',
    rotulo: 'Não cabe no meu bolso agora',
    gatilhos: ['nao cabe', 'ta fora do orcamento', 'nao tenho esse dinheiro', 'ta dificil pra mim', 'meu orcamento e menor', 'nao dou conta', 'nao tenho como pagar isso', 'esse mes ta apertado', 'minha renda nao da', 'nao tenho folga', 'ta acima do que posso', 'quero algo mais em conta'],
    fala: 'Se está fora do que cabe, o caminho não é forçar. Dá para mexer em prazo, em quilometragem contratada e em categoria de carro até chegar num valor que você paga sem apertar o mês. Prefiro ajustar o plano a te vender um problema.',
    devolucao: 'Qual valor mensal você pagaria sem sentir? Eu trabalho a partir dele.',
    evite: 'Insistir no mesmo plano. Sem ajustar prazo, km ou categoria, o cliente só repete o não e a conversa morre no preço.',
  },
  {
    id: 'so-com-desconto',
    familia: 'preco',
    rotulo: 'Só fecho se você baixar',
    gatilhos: ['me da um desconto', 'baixa um pouco', 'faz um precinho', 'tira um pouco', 'qual seu melhor preco', 'se der desconto eu fecho', 'abaixa ai que eu fecho', 'tem como melhorar', 'faz por menos', 'desconta ai', 'qual o melhor que voce faz', 'da um jeito no preco'],
    fala: 'Consigo trabalhar dentro do que a estrutura permite, e prefiro fazer isso mexendo no que muda o valor de verdade — prazo, quilometragem, categoria. Desconto que a empresa não sustenta vira problema no contrato depois.',
    devolucao: 'Se o valor chegar onde você precisa, assinamos hoje ou ainda falta alguma coisa?',
    evite: 'Ceder rápido ensina que o preço era inflado. Quem baixa sem contrapartida ouve o mesmo pedido de novo na assinatura.',
  },
  {
    id: 'entrada-caucao',
    familia: 'preco',
    rotulo: 'A entrada ou a caução pesou',
    gatilhos: ['tem entrada', 'precisa de entrada', 'caucao', 'deposito', 'tem que dar dinheiro na frente', 'nao tenho a entrada', 'por que tem entrada', 'adiantamento', 'valor inicial', 'primeira parcela maior', 'tem que pagar algo antes', 'sinal'],
    fala: 'Faz sentido perguntar. Esse valor inicial não some — a regra dele está escrita no contrato e eu te mostro a cláusula antes de você decidir. Se ele for o obstáculo real, dá para desenhar o plano de outro jeito.',
    devolucao: 'O incômodo é o valor em si ou o momento de tirar esse dinheiro do caixa?',
    evite: 'Falar da caução de passagem, como detalhe. Cliente que descobre depois sente que foi enrolado e derruba o negócio.',
  },
  {
    id: 'nao-fica-nada',
    familia: 'posse',
    rotulo: 'No fim não fica nada pra mim',
    gatilhos: ['no fim nao fica nada', 'paga e nao fica com nada', 'dinheiro jogado fora', 'e igual aluguel de casa', 'nao sobra nada', 'fico sem nada no final', 'joga dinheiro fora', 'perco tudo que paguei', 'no final devolvo e acabou', 'nao vira meu', 'sem retorno', 'nao fica nada no nome'],
    fala: 'Fica o uso, que é o que você contrata. No carro próprio também não fica tudo — boa parte do que você pagou vira desvalorização, imposto e oficina, e isso ninguém devolve. A diferença é que aqui esse custo aparece antes, não na revenda.',
    devolucao: 'Quando você vendeu seu último carro, saiu por perto do que você esperava?',
    evite: 'Prometer que assinatura é investimento. Não é, e o cliente percebe. Compare perda com perda em vez de inventar retorno.',
  },
  {
    id: 'heranca-patrimonio',
    familia: 'posse',
    rotulo: 'E a herança, o patrimônio da família',
    gatilhos: ['e a heranca', 'deixar pros filhos', 'patrimonio', 'bem no nome', 'meu filho fica com ele depois', 'construir patrimonio', 'bem material', 'fica pra familia', 'meus filhos herdam', 'quero deixar algo', 'e o meu patrimonio', 'bem duravel'],
    fala: 'Patrimônio se constrói com bem que segura valor, e carro faz o contrário — ele perde ano após ano. Se o objetivo é deixar algo, faz mais sentido o carro sair da conta de patrimônio e virar custo de uso, como energia ou plano de saúde.',
    devolucao: 'Você tiraria o carro da conta de patrimônio se isso liberasse dinheiro para o que valoriza?',
    evite: 'Ironizar a ideia de herança. Isso é valor de família, não erro de matemática. Reposicione o carro sem desqualificar o objetivo.',
  },
  {
    id: 'multa-rescisao',
    familia: 'compromisso',
    rotulo: 'E se eu quiser sair antes do prazo',
    gatilhos: ['e se eu quiser sair antes', 'tem multa', 'multa de rescisao', 'como faco pra cancelar', 'posso devolver antes', 'se eu desistir', 'quanto custa sair', 'rescisao', 'cancelamento', 'quero saber a multa', 'e se eu nao quiser mais', 'posso encerrar'],
    fala: 'Existe regra de encerramento antecipado e ela está escrita, não é decisão do vendedor no dia. Vou abrir essa parte com você agora e explicar como o valor é calculado, para você entrar sabendo qual é o custo do arrependimento.',
    devolucao: 'Quer que eu leia essa cláusula com você antes de falarmos de qualquer valor?',
    evite: 'Dizer que a multa é pequena sem mostrar a regra. Se o cliente sentir enrolação aqui, passa a duvidar de tudo que veio antes.',
  },
  {
    id: 'perder-emprego',
    familia: 'compromisso',
    rotulo: 'E se eu perder o emprego',
    gatilhos: ['e se eu perder o emprego', 'se eu for demitido', 'se eu ficar desempregado', 'e se a empresa me mandar embora', 'se apertar', 'se minha renda cair', 'e se eu nao puder pagar', 'fico sem trabalho e agora', 'estabilidade', 'se eu perder o cliente', 'futuro incerto', 'e se faltar dinheiro'],
    fala: 'Preocupação legítima, e vale a mesma pergunta para o financiamento — lá o bem é seu e a dívida também. Aqui existe caminho previsto para encerrar ou ajustar, e ele está no contrato. Melhor decidir olhando essa regra do que no escuro.',
    devolucao: 'Se você soubesse exatamente como encerrar num aperto, isso resolveria o receio?',
    evite: 'Passar por cima do medo com otimismo. Ele está falando de segurança, não de carro. Trate como risco real e mostre a saída.',
  },
  {
    id: 'letra-miuda',
    familia: 'compromisso',
    rotulo: 'Tenho medo da letra miúda',
    gatilhos: ['letra miuda', 'tem coisa escondida', 'o que ta escrito ali', 'tem asterisco', 'depois aparece taxa', 'sempre tem alguma coisa', 'quero ler tudo', 'manda o contrato pra eu ler', 'tem clausula escondida', 'nao confio no papel', 'o que nao ta escrito', 'surpresa depois'],
    fala: 'Você tem razão em querer ler. Eu mando o contrato inteiro antes da assinatura e prefiro que você leia com calma, ou com alguém de confiança. O que eu falo aqui precisa estar lá dentro, e é para você me cobrar se não estiver.',
    devolucao: 'Quer o contrato agora, por escrito, para conferir antes de qualquer proposta?',
    evite: 'Resumir o contrato de boca e empurrar a assinatura. Cliente desconfiado que assina no impulso cancela na primeira dúvida.',
  },
  {
    id: 'prazo-longo',
    familia: 'compromisso',
    rotulo: 'O prazo é longo demais pra mim',
    gatilhos: ['e muito tempo', 'prazo longo', 'nao sei onde vou estar', 'tanto tempo assim', 'tem prazo menor', 'quero por menos tempo', 'muitos meses', 'nao consigo enxergar tao longe', 'tem prazo curto', 'e ate quando', 'tempo demais', 'nao quero por tanto tempo'],
    fala: 'Prazo é escolha, não imposição — ele mexe no valor mensal e na regra de saída. Dá para desenhar mais curto e ver o efeito na mensalidade, para você decidir com o número na frente e não pela sensação de compromisso.',
    devolucao: 'Que horizonte de tempo você consegue enxergar com tranquilidade hoje?',
    evite: 'Vender só o prazo que rende mais. Prazo desconfortável vira pedido de rescisão e cliente perdido para sempre.',
  },
  {
    id: 'viajo-estrada',
    familia: 'km',
    rotulo: 'Viajo direto, pego muita estrada',
    gatilhos: ['viajo muito', 'pego estrada', 'vou pra praia todo fim de semana', 'viajo a trabalho', 'rodo estrada', 'vou pro interior sempre', 'viagem longa', 'dirijo pra outro estado', 'faco estrada direto', 'viajo com a familia', 'estrada toda semana', 'subo a serra sempre'],
    fala: 'Quem faz estrada tem duas preocupações reais — quilometragem contratada e o que acontece se der problema longe de casa. Dá para dimensionar o km pelas suas viagens e conferir no contrato como funciona a assistência fora da sua cidade.',
    devolucao: 'Quantas viagens longas você faz por mês e até onde costuma ir?',
    evite: 'Falar só de km e ignorar assistência em estrada. O medo de quem viaja é ficar parado longe, não o valor do excedente.',
  },
  {
    id: 'trabalho-app',
    familia: 'km',
    rotulo: 'Trabalho com aplicativo',
    gatilhos: ['trabalho de app', 'dirijo pra uber', 'faco 99', 'motorista de aplicativo', 'rodo por app', 'trabalho com passageiro', 'faco entrega', 'trabalho rodando', 'uso pra trabalhar', 'ganho a vida com o carro', 'faco corrida', 'aplicativo de transporte'],
    fala: 'Quem roda por aplicativo precisa de contrato feito para esse uso — quilometragem alta e regra clara sobre atividade remunerada. Isso muda o plano e não dá para fingir que é uso particular. Vou verificar a modalidade certa antes de passar valor.',
    devolucao: 'Você roda por app todos os dias ou só complementa a renda em alguns períodos?',
    evite: 'Vender plano particular para quem roda por app. Descoberto depois, o contrato quebra e o cliente fica na mão.',
  },
  {
    id: 'mudanca-cidade',
    familia: 'km',
    rotulo: 'Posso mudar de cidade no meio',
    gatilhos: ['posso mudar de cidade', 'vou me mudar', 'posso ser transferido', 'empresa pode me mandar pra outro estado', 'vou morar em outro lugar', 'e se eu mudar', 'talvez eu mude', 'empresa pode me transferir', 'mudanca de estado', 'vou pra outra cidade', 'nao sei se fico aqui', 'posso sair da cidade'],
    fala: 'Mudança não precisa quebrar o contrato, mas muda coisas práticas — onde você faz revisão e como fica a assistência na cidade nova. Vale verificar a cobertura no destino antes de assinar, não depois que a mudança já estiver marcada.',
    devolucao: 'Existe uma cidade provável de destino ou ainda é só uma possibilidade?',
    evite: 'Dizer que tanto faz onde ele mora. Se a rede não atende bem lá, o problema volta como reclamação e cancelamento.',
  },
  {
    id: 'estourar-franquia-km',
    familia: 'km',
    rotulo: 'E se eu estourar a franquia de km',
    gatilhos: ['e se eu passar do km', 'estourar o limite', 'passar da quilometragem', 'quanto custa o km a mais', 'excedente', 'se eu rodar mais', 'cobra por km extra', 'e se eu ultrapassar', 'km excedente', 'paga a mais como', 'limite estourado', 'como cobra o km'],
    fala: 'A regra do excedente está escrita e é cobrada por quilômetro rodado além do contratado. Por isso eu prefiro dimensionar com folga a segurar a mensalidade. Se o seu uso mudar no meio, verificamos se o seu pacote permite revisão.',
    devolucao: 'Prefere contratar com folga ou ficar no limite e pagar excedente quando acontecer?',
    evite: 'Tratar o excedente como detalhe pequeno. Cliente que leva susto na fatura não renova e ainda fala mal na rua.',
  },
  {
    id: 'franquia-sinistro',
    familia: 'seguro',
    rotulo: 'Se eu bater, quem paga o quê',
    gatilhos: ['se eu bater', 'quem paga a batida', 'participacao', 'franquia do seguro', 'se eu der uma amassada', 'e se acontecer um acidente', 'bati o carro e agora', 'quem cobre', 'sinistro', 'quem paga o conserto', 'se for minha culpa', 'risquei o carro'],
    fala: 'A proteção vem no contrato e existe um valor de participação em caso de sinistro — isso não é pegadinha, é como toda cobertura funciona. O que muda é você saber o valor antes. Vou te mostrar onde está descrito e quando ele se aplica.',
    devolucao: 'Quer que eu abra agora a parte de sinistro para você ver a regra inteira?',
    evite: 'Dizer que é tudo coberto. Na primeira batida a participação aparece e o cliente sente que foi enganado no fechamento.',
  },
  {
    id: 'roubo-furto',
    familia: 'seguro',
    rotulo: 'E se roubarem o carro',
    gatilhos: ['e se roubar', 'furto', 'levaram o carro', 'assalto', 'roubo de carro', 'aqui rouba muito', 'e se me tomarem o carro', 'na minha cidade rouba', 'medo de roubo', 'se levarem o carro', 'se for roubado eu pago', 'carro roubado'],
    fala: 'Roubo está entre os eventos previstos na cobertura, com regra própria e boletim de ocorrência. A vantagem prática é que você não fica com o prejuízo do bem, porque o carro não é seu. Vou te mostrar a cláusula e o passo a passo.',
    devolucao: 'Onde você costuma deixar o carro à noite e durante o horário de trabalho?',
    evite: 'Vender medo da região do cliente. Ele mora ali e se ofende. Fale do procedimento e da cobertura, não da violência dele.',
  },
  {
    id: 'perda-total',
    familia: 'seguro',
    rotulo: 'E se der perda total',
    gatilhos: ['perda total', 'carro destruido', 'se acabar o carro', 'batida forte', 'e se nao tiver conserto', 'deu total', 'carro perdido', 'e se destruir', 'acidente grave', 'se ficar sem conserto', 'carro nao tem mais jeito', 'bateu e acabou'],
    fala: 'Em perda total o bem que se perde é da empresa, não seu — isso muda bastante o tamanho do susto. Existe procedimento previsto e regra para a continuidade do contrato. Prefiro te explicar essa parte com o texto na frente do que de memória.',
    devolucao: 'Você já passou por perda total num carro próprio? Como foi resolver aquilo?',
    evite: 'Improvisar a explicação do procedimento. Nessa objeção o cliente mede a sua segurança. Chute aqui derruba a confiança inteira.',
  },
  {
    id: 'meu-seguro-mais-barato',
    familia: 'seguro',
    rotulo: 'Meu seguro sai bem mais barato',
    gatilhos: ['meu seguro e mais barato', 'pago pouco de seguro', 'meu corretor faz melhor', 'tenho bonus', 'seguro meu sai por menos', 'meu seguro e camarada', 'faco seguro com meu amigo', 'seguro nao e tao caro', 'tenho desconto no seguro', 'o seguro que pago e menor', 'meu premio e baixo', 'meu corretor cobra menos'],
    fala: 'Se você tem bônus e um bom corretor, seu prêmio é competitivo mesmo, não vou discutir isso. A conta muda quando entra o que o seguro não cobre — imposto, revisão, desgaste e a queda de valor do carro. É esse conjunto que a mensalidade substitui.',
    devolucao: 'Fora o seguro, quanto o carro te custou no último ano em imposto e oficina?',
    evite: 'Duvidar do valor que ele cita. Ele sabe quanto paga. Amplie a conta para além do seguro em vez de contestar o número dele.',
  },
  {
    id: 'oficina-credenciada',
    familia: 'manutencao',
    rotulo: 'Onde eu levo o carro pra revisão',
    gatilhos: ['onde levo pra revisao', 'qual oficina', 'tem que ir na concessionaria', 'levo onde', 'meu mecanico de confianca', 'tem oficina perto', 'onde faz manutencao', 'quem faz a revisao', 'tenho que marcar', 'posso levar no meu mecanico', 'rede credenciada', 'assistencia tecnica'],
    fala: 'A manutenção é feita em rede credenciada, com agendamento, e isso existe para garantir peça e histórico do carro. Vale conferirmos agora qual é o ponto mais perto de você, porque distância é o que realmente incomoda no dia a dia.',
    devolucao: 'Qual região fica melhor para você deixar o carro num dia de revisão?',
    evite: 'Prometer que ele pode usar o mecânico dele. Não pode, e essa promessa vira atrito logo na primeira revisão.',
  },
  {
    id: 'carro-reserva',
    familia: 'manutencao',
    rotulo: 'Fico a pé enquanto conserta?',
    gatilhos: ['fico a pe', 'e se o carro quebrar', 'tem carro reserva', 'como eu me viro', 'fico sem carro', 'preciso do carro todo dia', 'e enquanto conserta', 'me da outro carro', 'carro substituto', 'fico na mao', 'nao posso ficar sem carro', 'tem reserva'],
    fala: 'Existe previsão de carro reserva e ela tem regra — prazo e tipo de ocorrência que dão direito. Como você depende do carro todo dia, vale ler essa parte comigo agora, para você saber exatamente em que situação ele entra.',
    devolucao: 'Quantos dias sem carro seriam um problema de verdade na sua rotina?',
    evite: 'Falar que sempre tem reserva. A regra tem condição e prazo. Prometer demais aqui gera reclamação e pedido de cancelamento.',
  },
  {
    id: 'pneu-desgaste',
    familia: 'manutencao',
    rotulo: 'Pneu e desgaste, quem paga',
    gatilhos: ['quem paga o pneu', 'pneu ta incluso', 'pastilha de freio', 'desgaste', 'troca de pneu e por minha conta', 'alinhamento', 'bateria quem troca', 'troca de oleo', 'o que ta incluso na manutencao', 'revisao inclui o que', 'peca de desgaste', 'furou o pneu quem paga'],
    fala: 'Isso precisa ficar claro antes de assinar, não depois. Manutenção preventiva e itens de desgaste têm regra específica no contrato, item por item. Prefiro abrir essa lista com você agora para não sobrar dúvida sobre o que é seu e o que é nosso.',
    devolucao: 'Quer que eu leia com você a lista do que está incluso e do que fica por sua conta?',
    evite: 'Responder que está tudo incluso. Mau uso e alguns consumíveis não estão, e a fatura mostra isso no pior momento possível.',
  },
  {
    id: 'socio-decide',
    familia: 'terceiro',
    rotulo: 'Meu sócio decide junto comigo',
    gatilhos: ['tenho que falar com meu socio', 'meu socio decide', 'decisao da sociedade', 'somos dois na empresa', 'meu socio precisa ver', 'levo pra reuniao', 'decidimos juntos', 'a diretoria decide', 'meu socio manda no financeiro', 'vou apresentar pro socio', 'precisa da aprovacao dele', 'o conselho decide'],
    fala: 'Faz sentido, e proposta que entra em reunião precisa estar pronta para ser lida sem mim na sala. Vou te mandar o material com a comparação e com o que a empresa deixa de gastar em outras frentes, no formato que seu sócio avalia rápido.',
    devolucao: 'O que pesa mais para ele: o valor mensal, o prazo ou o tratamento contábil?',
    evite: 'Mandar só o valor. Sócio que recebe número solto responde não por falta de contexto, e você nem fica sabendo o motivo.',
  },
  {
    id: 'contador-decide',
    familia: 'terceiro',
    rotulo: 'Vou ver isso com meu contador',
    gatilhos: ['vou falar com meu contador', 'meu contador ve isso', 'preciso da opiniao do contador', 'mando pro contador', 'meu contador cuida disso', 'tenho que perguntar pra contabilidade', 'o escritorio contabil decide', 'vou passar pro contador', 'minha contabilidade analisa', 'depende do contador', 'ele cuida dos numeros', 'minha contadora ve'],
    fala: 'Ótimo, é a pessoa certa para olhar isso. Posso preparar o material com a natureza do contrato e a documentação que ele vai pedir, para a análise não travar por falta de informação. Assim ele responde rápido em vez de deixar parado.',
    devolucao: 'Quer que eu fale direto com ele para adiantar as dúvidas técnicas?',
    evite: 'Discutir contabilidade sem base. Se você errar um termo com o contador, a proposta inteira perde credibilidade na hora.',
  },
  {
    id: 'pai-acha-melhor',
    familia: 'terceiro',
    rotulo: 'Meu pai acha melhor comprar',
    gatilhos: ['meu pai acha', 'meu pai falou pra comprar', 'na minha familia sempre comprou', 'meu sogro disse', 'meu pai entende de carro', 'vou perguntar pro meu pai', 'ele acha que e furada', 'meu pai nunca alugou', 'minha familia acha estranho', 'meu irmao disse', 'meu tio falou', 'em casa ninguem gosta disso'],
    fala: 'A experiência dele é real e vem de um tempo em que comprar era o único caminho. O contexto mudou — imposto, seguro e oficina hoje pesam de outro jeito. Vale a conversa com ele olhando as contas de agora, não a lembrança de antes.',
    devolucao: 'Ele decide junto com você ou é uma opinião que você quer respeitar?',
    evite: 'Colocar o cliente contra a família. Ele escolhe a família e some. Traga o terceiro para a conversa em vez de disputar.',
  },
  {
    id: 'ja-uso-outra-locadora',
    familia: 'concorrente',
    rotulo: 'Já assino com outra empresa',
    gatilhos: ['ja tenho com outra', 'ja sou cliente da outra', 'ja assino em outro lugar', 'estou com outra locadora', 'ja uso o servico de outra', 'meu carro ja e de assinatura', 'estou satisfeito com a atual', 'ja tenho contrato la', 'nao preciso trocar', 'estou bem atendido', 'ja fecho com eles', 'sou cliente antigo la'],
    fala: 'Então a decisão de modelo você já tomou, o que simplifica a conversa. O que costuma variar entre empresas é o atendimento na hora do problema, o prazo de reserva e como o contrato trata a renovação. Posso te mostrar como fica no próximo ciclo.',
    devolucao: 'Quando vence o seu contrato atual e o que você mudaria nele se pudesse?',
    evite: 'Atacar a empresa atual. Cliente satisfeito defende quem o atende. Pergunte pelo vencimento e pelo que incomoda hoje.',
  },
  {
    id: 'marca-conhecida',
    familia: 'concorrente',
    rotulo: 'Prefiro empresa grande e conhecida',
    gatilhos: ['prefiro empresa grande', 'so conheco as grandes', 'nunca ouvi falar de voces', 'empresa conhecida e mais segura', 'voces sao pequenos', 'marca forte', 'nome de mercado', 'empresa nova me da medo', 'quero uma que todo mundo conhece', 'tamanho da empresa', 'de confianca mesmo', 'quem garante voces'],
    fala: 'Tamanho tranquiliza, é razoável. Na prática quem sustenta a segurança é o contrato, a titularidade do veículo e a estrutura de atendimento — e isso dá para verificar em documento. Prefiro que você confira a acreditar na minha palavra.',
    devolucao: 'Que tipo de comprovação te deixaria seguro para seguir a conversa?',
    evite: 'Prometer que somos iguais às grandes. Ofereça verificação, documento e contrato, que é o que responde a essa dúvida.',
  },
  {
    id: 'manda-no-zap',
    familia: 'adiamento',
    rotulo: 'Me manda no zap que eu vejo',
    gatilhos: ['manda no zap', 'me manda no whatsapp', 'passa no zap', 'manda por mensagem', 'me envia depois', 'manda ai que eu olho', 'zap', 'me manda o orcamento', 'manda a proposta ai', 'depois eu abro', 'manda que eu vejo com calma', 'me chama la'],
    fala: 'Mando agora mesmo. Só combino uma coisa: mensagem sem contexto vira arquivo esquecido. Vou enviar o resumo com os pontos que importam para o seu caso e marcar um horário rápido para tirar dúvida, mesmo que a resposta seja não.',
    devolucao: 'Que dia e horário eu te chamo para fecharmos isso de vez, sim ou não?',
    evite: 'Mandar o arquivo e esperar. Sem próximo passo marcado, a proposta morre entre a conversa de família e o grupo do trabalho.',
  },
  {
    id: 'depois-eu-vejo',
    familia: 'adiamento',
    rotulo: 'Agora não é hora, depois eu vejo',
    gatilhos: ['agora nao da', 'depois eu vejo', 'mais pra frente', 'ano que vem', 'quem sabe depois', 'esse ano nao', 'to sem tempo agora', 'depois do carnaval', 'quando as coisas melhorarem', 'mais tarde eu resolvo', 'agora nao e o momento', 'daqui uns meses'],
    fala: 'Sem problema em esperar, desde que a espera seja escolha e não fuga do assunto. Enquanto isso o carro atual continua consumindo imposto, seguro e oficina. Vale eu deixar a simulação registrada e te procurar na data que você definir.',
    devolucao: 'Que data faz sentido para retomarmos? Eu anoto e te procuro nela.',
    evite: 'Aceitar o depois sem data. Sem compromisso de calendário o cliente não volta e você perde todo o histórico da conversa.',
  },
  {
    id: 'sumiu-apos-proposta',
    familia: 'adiamento',
    rotulo: 'Sumiu depois de receber a proposta',
    gatilhos: ['desculpa a demora', 'sumi mesmo', 'tava corrido aqui', 'nao tive tempo de ver', 'depois eu olho isso', 'to enrolado', 'perdi a mensagem', 'nem abri ainda', 'desculpa nao respondi', 'to sem tempo', 'ainda nao vi', 'me perdi aqui'],
    fala: 'Sem cobrança, semana cheia acontece. Só preciso saber se ainda faz sentido para você ou se o momento passou — as duas respostas me servem. Se fizer sentido, retomo do ponto onde paramos e não repito o que você já sabe.',
    devolucao: 'Me diz só uma coisa: seguimos agora ou arquivo por enquanto?',
    evite: 'Insistir com mensagem de cobrança. Peça uma decisão fácil de dar, inclusive o não, para liberar o cliente ou a sua agenda.',
  },
  {
    id: 'nome-restrito',
    familia: 'credito',
    rotulo: 'Meu nome está com restrição',
    gatilhos: ['meu nome ta sujo', 'tenho restricao', 'to negativado', 'serasa', 'nome no spc', 'tenho pendencia', 'meu score e baixo', 'fui negativado', 'to com o nome restrito', 'tenho divida em aberto', 'meu cpf ta com problema', 'tenho protesto'],
    fala: 'Obrigado por dizer antes, isso economiza tempo dos dois lados. Restrição não fecha a porta de forma automática, depende do que é e do que a análise enxerga. Também existe caminho com outro titular ou pela pessoa jurídica, quando for o caso.',
    devolucao: 'É algo antigo, já resolvido, ou uma pendência que segue aberta hoje?',
    evite: 'Reagir com desconforto. Quem admite restrição está confiando em você. Constrangimento aqui encerra a relação na hora.',
  },
  {
    id: 'autonomo-sem-comprovar',
    familia: 'credito',
    rotulo: 'Sou autônomo, não comprovo renda',
    gatilhos: ['sou autonomo', 'nao tenho holerite', 'nao comprovo renda', 'trabalho por conta', 'sou informal', 'nao tenho carteira assinada', 'meu dinheiro e no pix', 'faco bico', 'nao declaro tudo', 'como comprovo renda', 'nao tenho contracheque', 'trabalho por fora'],
    fala: 'Autônomo é boa parte de quem contrata, então isso aqui é rotina. A comprovação aceita outros documentos além de holerite. Eu te digo exatamente o que serve no seu caso antes de você juntar papel à toa e se cansar do processo.',
    devolucao: 'Você tem movimentação bancária ou declaração no seu nome para usarmos?',
    evite: 'Pedir holerite de quem não tem. O cliente entende que não é para ele e desiste antes de descobrir que existe outro caminho.',
  },
  {
    id: 'mei-recente',
    familia: 'credito',
    rotulo: 'Meu MEI é novo, abri agora',
    gatilhos: ['meu mei e novo', 'abri o cnpj esse ano', 'empresa recem aberta', 'cnpj novo', 'tenho pouco tempo de empresa', 'abri agora', 'minha empresa e recente', 'mei recente', 'nao tenho faturamento ainda', 'empresa nova', 'acabei de abrir', 'cnpj com pouco tempo'],
    fala: 'Tempo de empresa entra na análise, é verdade, mas não é o único critério e existe a alternativa pela pessoa física. Antes de você desanimar, vale rodar as duas leituras e ver qual caminho responde melhor para o seu caso.',
    devolucao: 'Prefere que eu analise pelo CNPJ, pelo CPF ou pelos dois em paralelo?',
    evite: 'Descartar CNPJ novo de cara. Muita empresa recente tem sócio com histórico forte e o negócio sai pela pessoa física.',
  },
  {
    id: 'contador-nao-recomenda',
    familia: 'pj',
    rotulo: 'Meu contador não recomenda',
    gatilhos: ['meu contador nao recomenda', 'ele disse que nao vale', 'contador falou pra nao fazer', 'contabilidade nao aprovou', 'ele acha melhor comprar no cnpj', 'contador nao gostou', 'disse que e ruim pra empresa', 'ele nao indicou', 'meu contador e contra', 'contabilidade desaconselha', 'ele falou pra evitar', 'o escritorio nao recomendou'],
    fala: 'Vale entender o motivo, porque a recomendação muda conforme o regime da empresa e o uso do veículo. Prefiro conversar direto com ele, com o contrato na mão, a ficar no telefone sem fio. Se a leitura dele se sustentar, eu digo isso a você.',
    devolucao: 'Você sabe qual foi o argumento dele? Isso me ajuda a responder no ponto certo.',
    evite: 'Contrariar o contador na frente do cliente. Ele confia no profissional dele, não em você. Fale com o contador direto.',
  },
  {
    id: 'simples-nacional',
    familia: 'pj',
    rotulo: 'Minha empresa é do Simples',
    gatilhos: ['sou do simples', 'simples nacional', 'nao abato nada', 'nao aproveito no simples', 'meu regime e simples', 'nao deduzo despesa', 'nao tem beneficio pra mim', 'lucro presumido', 'nao entra no meu regime', 'nao serve pro simples', 'nao tem vantagem fiscal', 'imposto nao muda'],
    fala: 'No Simples o efeito tributário realmente não é o argumento, e não vou vender vantagem que não existe para o seu regime. O que continua valendo é previsibilidade de caixa, uso do capital de giro e não imobilizar dinheiro em veículo.',
    devolucao: 'Para a sua empresa hoje, o que aperta mais: o caixa mensal ou o capital parado?',
    evite: 'Prometer benefício fiscal genérico para PJ. No Simples isso não se sustenta e o contador desmonta a proposta inteira.',
  },
  {
    id: 'nota-para-deduzir',
    familia: 'pj',
    rotulo: 'Preciso de nota para lançar',
    gatilhos: ['tem nota fiscal', 'emite nota', 'preciso de nota pra empresa', 'como lanco na contabilidade', 'nota fiscal mensal', 'comprovante fiscal', 'documento pra contabilidade', 'precisa entrar no cnpj', 'nota em nome da empresa', 'como declaro isso', 'lancamento contabil', 'recibo'],
    fala: 'O contrato é empresarial e gera documento fiscal mensal em nome da empresa, o que dá lastro para o lançamento contábil. Como o tratamento depende do regime, quem define a classificação é o seu contador, com o contrato na frente.',
    devolucao: 'Quer que eu envie o modelo de contrato para a sua contabilidade avaliar?',
    evite: 'Afirmar como a despesa deve ser classificada. Isso é decisão do contador e errar aqui compromete a sua credibilidade.',
  },
  {
    id: 'aluguel-disfarcado',
    familia: 'confianca',
    rotulo: 'Isso é aluguel disfarçado',
    gatilhos: ['isso e aluguel', 'aluguel disfarcado', 'e locadora normal', 'so mudou o nome', 'e a mesma coisa que alugar', 'nome bonito pra aluguel', 'voces alugam carro', 'isso nao e novidade', 'e locacao mesmo', 'aluguel mensal', 'chamam de assinatura mas e aluguel', 'e so um aluguel'],
    fala: 'É locação sim, e não tem por que esconder isso. A diferença está no prazo, no que vem embutido e no fato de o carro ser dedicado a você. O nome importa menos que o escopo, e é o escopo que eu quero abrir com você agora.',
    devolucao: 'Se o contrato entregar o que descrevi, o nome muda alguma coisa para você?',
    evite: 'Negar que é locação. É locação, e o cliente que descobre sozinho passa a duvidar de tudo que você disse antes disso.',
  },
  {
    id: 'empresa-vai-quebrar',
    familia: 'confianca',
    rotulo: 'E se a empresa quebrar',
    gatilhos: ['e se voces quebrarem', 'e se a empresa fechar', 'e se sumirem com o carro', 'e se falir', 'quem garante', 'e se der problema com a empresa', 'voces sao solidos', 'empresa nova quebra', 'fico sem carro se fechar', 'risco da empresa', 'quebrou e agora', 'que garantia eu tenho'],
    fala: 'Pergunta justa quando se assina contrato longo. O veículo tem titularidade registrada e o contrato define o que acontece em cada cenário. Posso te mostrar a documentação da empresa e a cláusula que trata disso, para você avaliar com dado.',
    devolucao: 'Que documento te daria segurança para seguir: contrato, registro ou os dois?',
    evite: 'Rir da pergunta ou tratar como paranoia. O cliente está avaliando risco, que é exatamente o que um adulto deve fazer.',
  },
  {
    id: 'modelo-novidade',
    familia: 'confianca',
    rotulo: 'Nunca ouvi falar disso, é novo',
    gatilhos: ['nunca ouvi falar', 'isso e novo', 'nao conheco esse modelo', 'nunca vi ninguem fazer', 'e moda', 'sera que pega', 'isso funciona mesmo', 'conheco pouco disso', 'primeira vez que ouco falar', 'e coisa de gringo', 'aqui ninguem usa isso', 'sera que isso vinga'],
    fala: 'É natural estranhar o que ainda não circula no seu meio. O modelo já roda há bastante tempo em frota de empresa e chegou depois na pessoa física. Prefiro te mostrar como funciona na prática a te convencer de que é tendência.',
    devolucao: 'O que você precisaria ver funcionando para deixar de parecer novidade?',
    evite: 'Vender futuro e modernidade. Quem estranha novidade quer prova concreta, não discurso de tendência de mercado.',
  },
  {
    id: 'tem-pegadinha',
    familia: 'confianca',
    rotulo: 'Isso aí tem pegadinha',
    gatilhos: ['tem pegadinha', 'ta bom demais', 'onde ta o truque', 'qual a jogada', 'bonito demais pra ser verdade', 'tem coisa ai', 'cheiro de furada', 'isso e cilada', 'alguma coisa tem', 'onde eu vou me dar mal', 'conta a verdade', 'qual o porem'],
    fala: 'Tem porém sim, e prefiro dizer antes: existe prazo, existe regra de quilometragem, existe participação em sinistro e existe custo para sair antes. Nada disso fica escondido. Se essas quatro coisas te incomodam, o modelo não é para você.',
    devolucao: 'Dessas condições, qual delas mais te incomodaria no dia a dia?',
    evite: 'Responder que não tem nenhum porém. Quem desconfia quer ouvir os limites. Só a lista de restrições devolve a confiança.',
  },
  {
    id: 'modelo-indisponivel',
    familia: 'veiculo',
    rotulo: 'Queria outro modelo de carro',
    gatilhos: ['queria outro modelo', 'nao gostei desse carro', 'tem esse outro', 'so tem esse', 'queria um suv', 'queria automatico', 'nao tem o que eu quero', 'meu sonho e outro carro', 'tem carro maior', 'queria um sedan', 'nao curto essa marca', 'tem outra opcao de carro'],
    fala: 'Faz diferença sim, carro é uso diário. Posso verificar a disponibilidade do modelo que você quer e o efeito dele no valor mensal, para você comparar com o que já está na mesa em vez de decidir por eliminação.',
    devolucao: 'Qual modelo você tinha em mente e o que ele resolve que este não resolve?',
    evite: 'Forçar o carro que está disponível. Cliente que assina o carro errado reclama o contrato inteiro e não renova depois.',
  },
  {
    id: 'cor-versao',
    familia: 'veiculo',
    rotulo: 'Não gosto da cor ou da versão',
    gatilhos: ['so tem branco', 'nao gosto dessa cor', 'queria preto', 'queria a versao completa', 'essa versao e basica', 'tem banco de couro', 'nao tem multimidia', 'queria com teto solar', 'essa cor nao me agrada', 'versao de entrada', 'tem opcional', 'queria mais completo'],
    fala: 'Cor e versão têm disponibilidade variável e mexem no prazo de entrega e no valor. Consigo verificar o que existe dentro do seu prazo e o que muda na mensalidade se você segurar um pouco para pegar exatamente o que quer.',
    devolucao: 'Prefere receber antes, com o que há disponível, ou esperar a configuração exata?',
    evite: 'Tratar cor como capricho. Para muita gente é o item que decide, e desdenhar disso esfria o cliente já no fim do processo.',
  },
  {
    id: 'prazo-entrega',
    familia: 'veiculo',
    rotulo: 'Demora demais pra entregar',
    gatilhos: ['demora pra entregar', 'quanto tempo pra chegar', 'preciso do carro agora', 'nao posso esperar', 'prazo de entrega', 'quando eu recebo', 'tem pronta entrega', 'fila de espera', 'meu carro ja foi vendido', 'preciso pra semana que vem', 'e urgente', 'tem disponivel agora'],
    fala: 'Prazo depende do modelo e da disponibilidade, e prefiro te dar a data real a te agradar agora e te frustrar depois. Se a urgência é grande, vale olhar o que já está disponível e comparar com o que você esperaria receber.',
    devolucao: 'Até que data você precisa estar com carro na mão, de fato?',
    evite: 'Chutar prazo para segurar o cliente. Data combinada errada destrói o começo da relação e vira reclamação imediata.',
  },
  {
    id: 'carro-ja-rodado',
    familia: 'veiculo',
    rotulo: 'O carro é usado, já rodado',
    gatilhos: ['o carro e usado', 'ja rodou muito', 'quem dirigiu antes', 'carro de outro cliente', 'e seminovo', 'o carro tem quantos km', 'nao quero carro usado', 'quero zero km', 'carro de locadora e judiado', 'ja foi de outra pessoa', 'carro rodado', 'e novo mesmo'],
    fala: 'Pergunta certa, e a resposta muda o preço. Existe carro novo e existe carro que já rodou em contrato anterior, com histórico de manutenção registrado. Eu te digo exatamente qual é o caso desta proposta antes de seguirmos.',
    devolucao: 'Você aceitaria um carro já rodado se o histórico de manutenção fosse documentado?',
    evite: 'Fugir da pergunta. A dúvida sobre carro de locadora é antiga e forte. Responda direto e mostre o histórico do veículo.',
  },
  {
    id: 'dar-carro-de-entrada',
    familia: 'troca',
    rotulo: 'Quero dar meu carro de entrada',
    gatilhos: ['tenho um carro pra dar de entrada', 'aceita meu carro', 'pega o meu na troca', 'quero dar de entrada', 'meu carro entra como parte', 'aceita troca', 'faz avaliacao do meu', 'meu usado abate', 'quanto voces dao pelo meu', 'troco o meu', 'tem entrada com carro', 'meu carro vale quanto'],
    fala: 'Na assinatura não existe entrada em veículo, porque não há compra de bem. O seu carro continua seu e costuma render mais vendido no mercado do que dado como parte de pagamento. Posso te orientar sobre isso mesmo sem ficar com ele.',
    devolucao: 'Você já pensou em vender o seu por fora e usar esse dinheiro para outra coisa?',
    evite: 'Improvisar uma avaliação para agradar. Se você não compra o carro, criar expectativa de troca gera frustração e desconfiança.',
  },
  {
    id: 'carro-nao-quitado',
    familia: 'troca',
    rotulo: 'Meu carro ainda não está quitado',
    gatilhos: ['meu carro ta financiado', 'ainda devo parcelas', 'to pagando o meu ainda', 'falta quitar', 'tenho financiamento em aberto', 'meu carro nao ta quitado', 'devo no banco', 'tenho consorcio pra pagar', 'como faco com o financiamento', 'tenho parcela do carro', 'carro alienado', 'ainda ta no nome do banco'],
    fala: 'Faz sentido resolver isso antes de qualquer assinatura. A conta real é a diferença entre continuar pagando o seu carro e a mensalidade daqui, considerando quanto sobra se você vender e quitar o que falta.',
    devolucao: 'Quanto falta de parcelas e quanto o mercado está pagando pelo seu carro hoje?',
    evite: 'Sugerir assinar sem resolver a dívida. Duas contas de carro no mesmo mês quebram o cliente e o contrato vem abaixo.',
  },
  {
    id: 'gosto-do-meu-carro',
    familia: 'emocional',
    rotulo: 'Gosto do meu carro, tenho apego',
    gatilhos: ['gosto do meu carro', 'tenho apego', 'meu carro e bom', 'ele nunca me deixou na mao', 'cuido dele demais', 'conheco cada barulho dele', 'comprei com sacrificio', 'meu carro e novo ainda', 'nao quero me desfazer', 'ele ja ta pago', 'ele e da familia', 'tenho carinho por ele'],
    fala: 'Apego por carro é real e não é besteira. A conversa nem precisa ser sobre trocar hoje. Vale você saber quanto ele custa por mês entre imposto, seguro e oficina, e decidir com essa informação quando fizer sentido para você.',
    devolucao: 'Se o carro fosse só um número por mês, ele ainda valeria o que custa hoje?',
    evite: 'Falar mal do carro dele. É o mesmo que criticar a escolha e a história dele. Fale de custo, nunca do carro em si.',
  },
  {
    id: 'personalizar-acessorios',
    familia: 'emocional',
    rotulo: 'Quero som, película, acessório',
    gatilhos: ['quero por som', 'pelicula', 'quero personalizar', 'engate', 'rack', 'quero mexer no carro', 'insulfilm', 'som automotivo', 'acessorio', 'posso instalar', 'quero rodas maiores', 'protetor de cacamba'],
    fala: 'Alteração tem regra, porque o carro volta no fim do contrato. Alguns itens são autorizados mediante aprovação e remoção depois, outros não. Melhor você me dizer o que pretende instalar para eu confirmar item por item antes de assinar.',
    devolucao: 'O que você instalaria de fato já no primeiro mês? Confirmo cada um deles.',
    evite: 'Dizer que pode tudo. Devolução com alteração não autorizada gera cobrança e briga no fim de um contrato que ia bem.',
  },
  {
    id: 'adesivo-empresa',
    familia: 'emocional',
    rotulo: 'Preciso adesivar com a marca',
    gatilhos: ['preciso adesivar', 'logo da empresa no carro', 'plotagem', 'adesivo da minha empresa', 'envelopamento', 'carro da frota tem que ter marca', 'identificacao visual', 'pintura personalizada', 'carro de divulgacao', 'marca no carro', 'adesivar a frota', 'comunicacao visual'],
    fala: 'Adesivagem costuma ser tratada como alteração e depende de autorização prévia, com regra de remoção na devolução. Como isso é operacional para a sua empresa, prefiro confirmar por escrito antes de você fechar e planejar a frota.',
    devolucao: 'Quantos carros teriam identificação visual e com que frequência ela muda?',
    evite: 'Autorizar plotagem de boca. Custo de remoção e marca de adesivo na pintura viram cobrança na devolução da frota inteira.',
  },
  {
    id: 'devolver-no-fim',
    familia: 'emocional',
    rotulo: 'No fim vou ter que devolver',
    gatilhos: ['vou ter que devolver', 'entregar o carro no final', 'perder o carro depois', 'acostumo e devolvo', 'e ruim devolver', 'meus filhos vao se acostumar', 'fico sem carro no fim', 'tenho que entregar', 'no final entrego e fico sem nada', 'e chato entregar', 'no final devolvo', 'perco o carro no fim'],
    fala: 'Devolver faz parte do desenho, e o fim do contrato costuma ser o momento de escolher outro carro, mais novo. Quem compra também troca um dia — a diferença é que aqui você não passa pelo processo de vender o usado.',
    devolucao: 'Trocar de carro com mais frequência te agrada ou te incomoda de verdade?',
    evite: 'Ignorar o vínculo afetivo. Quem se apega antecipa a perda. Mostre o fim do ciclo como escolha, não como despedida.',
  },
  {
    id: 'cidade-sem-loja',
    familia: 'regional',
    rotulo: 'Não tem loja na minha cidade',
    gatilhos: ['nao tem loja aqui', 'voces atendem minha cidade', 'fica longe de mim', 'moro no interior', 'aqui nao tem unidade', 'tem filial perto', 'so tem na capital', 'minha cidade e pequena', 'atende minha regiao', 'teria que ir longe', 'fica a horas daqui', 'tem representante aqui'],
    fala: 'Cobertura é o primeiro ponto a verificar, antes de valor. Não adianta o plano ser bom e a operação ficar longe de você. Vou conferir o atendimento para o seu endereço e te dizer com franqueza se atendemos bem a sua região.',
    devolucao: 'Qual é a sua cidade e qual capital fica mais perto de você?',
    evite: 'Fechar contrato onde a rede é fraca. A primeira revisão vira transtorno e o cliente cancela falando mal do serviço.',
  },
  {
    id: 'assistencia-longe',
    familia: 'regional',
    rotulo: 'Aqui o socorro demora a chegar',
    gatilhos: ['aqui demora pra chegar socorro', 'guincho demora', 'assistencia nao vem aqui', 'ninguem atende essa regiao', 'fico na mao aqui', 'guincho nao chega', 'aqui e longe de tudo', 'socorro nao cobre aqui', 'estrada ruim e ninguem vem', 'aqui e distante', 'atendimento demora na minha regiao', 'nao tem guincho aqui'],
    fala: 'Se a sua experiência é essa, cobrar prazo é o ponto certo. Assistência tem raio e prazo definidos, e isso muda conforme a região. Vou verificar como fica no seu endereço antes de falarmos de plano, para você não comprar promessa.',
    devolucao: 'Onde você mais roda: dentro da cidade, na estrada ou em zona rural?',
    evite: 'Prometer atendimento rápido sem checar a região. No interior o cliente conhece a realidade melhor que a tabela de cobertura.',
  },
  {
    id: 'estrada-de-terra',
    familia: 'regional',
    rotulo: 'Aqui é estrada de terra e roça',
    gatilhos: ['estrada de terra', 'aqui e roca', 'vou pra fazenda', 'chao de terra', 'estrada ruim', 'carro sofre aqui', 'preciso de carro alto', 'aqui e sitio', 'poeira e buraco', 'carro de cidade nao aguenta', 'zona rural', 'estrada sem asfalto'],
    fala: 'Uso em terra castiga suspensão e pneu, e isso conversa com a escolha de categoria e com a regra de mau uso na devolução. Prefiro dizer isso antes de fechar: com esse tipo de estrada, categoria errada vira cobrança lá na frente.',
    devolucao: 'Quantos dias por semana você anda em terra e por quantos quilômetros?',
    evite: 'Vender carro de passeio para uso rural pesado. A devolução vira discussão de avaria e o cliente sai revoltado da loja.',
  },
];
